name: Nix Flake actions

on:
  pull_request:
    paths:
      - 'crates/**'
      - 'Cargo.lock'
      - 'flake.lock'
      - '.github/workflows/nix-github-actions.yml'
  push:
    paths:
      - 'crates/**'
      - 'Cargo.lock'
      - 'flake.lock'
      - '.github/workflows/nix-github-actions.yml'

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Configure containerd socket permissions
        run: |
          sudo apt-get install -y containerd.io
          sudo systemctl status containerd
          whoami
          groups
          sudo chmod g+w /run/containerd/containerd.sock
          sudo chgrp docker /run/containerd/containerd.sock
          ls -l /run/containerd/containerd.sock
          docker version
      - name: Configure containerd
        run: |
          sudo sed -i '/^\[plugins\."io.containerd.grpc.v1.cri".containerd.runtimes.runc\]/a \\
            \ \ [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options] \\
            \ \ \ \ Mounts = [ \\
            \ \ \ \ \ \ { source = "/nix", destination = "/nix", type = "bind", options = ["bind", "rw"] }, \\
            \ \ \ \ \ \ { source = "/etc/nix", destination = "/etc/nix", type = "bind", options = ["bind", "rw"] }, \\
            \ \ \ \ \ \ { source = "/home", destination = "/home", type = "bind", options = ["bind", "rw"] } \\
            \ \ \ \ ]' /etc/containerd/config.toml
          sudo systemctl restart containerd
      - name: Build Nix package
        run: nix build -L '.#${{ matrix.attr }}'
        env:
          SOCKET_PATH: /run/containerd/containerd.sock
