name: Nix Flake actions

on:
  pull_request:
    paths:
      - 'crates/**'
      - 'Cargo.lock'
      - 'flake.lock'
      - '.github/workflows/nix-github-actions.yml'
  push:
    paths:
      - 'crates/**'
      - 'Cargo.lock'
      - 'flake.lock'
      - '.github/workflows/nix-github-actions.yml'

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            build-users-group = nixbld
      - name: Configure containerd socket permissions
        run: |
          sudo apt-get install -y containerd.io
          sudo systemctl start containerd
          sudo systemctl status containerd
          sudo mkdir -p /etc/systemd/system/containerd.service.d/
          containerd config default | sudo tee /etc/containerd/config.toml
          sudo sed -i 's/^grpc_gid.*$/grpc_gid = 118/' /etc/containerd/config.toml
          sudo systemctl restart containerd

          timeout 10 bash -c 'until [[ -S /run/containerd/containerd.sock ]]; do sleep 1; done'

          echo '[Service]' | sudo tee /etc/systemd/system/containerd.service.d/override.conf
          echo 'ExecStartPost=/bin/chgrp docker /run/containerd/containerd.sock' | sudo tee -a /etc/systemd/system/containerd.service.d/override.conf
          echo 'ExecStartPost=/bin/chmod g+w /run/containerd/containerd.sock' | sudo tee -a /etc/systemd/system/containerd.service.d/override.conf
          sudo systemctl daemon-reload
          sudo systemctl restart containerd
          timeout 10 bash -c 'until [[ -S /run/containerd/containerd.sock ]]; do sleep 1; done'
          sudo usermod -aG docker runner || true
          ls -l /run/containerd/containerd.sock
          sudo chmod 666 /run/containerd/containerd.sock
          sudo chgrp docker /run/containerd/containerd.sock
          ls -l /run/containerd/containerd.sock
          sudo -E env "PATH=$PATH" "NIX_PATH=$NIX_PATH" test -w /run/containerd/containerd.sock && echo "Writable" || echo "Protected"
      - name: Setup CNI configuration
        run: |
          sudo mkdir -p /var/run/netns
          sudo chmod 777 /var/run/netns
          ls -l /var/run/netns
          sudo mkdir -p /etc/cni/net.d
          sudo ctr namespaces create default
          sudo ctr namespaces create moby
          sudo ctr namespaces ls
      - name: Build Nix package
        run: |
          export SOCKET_PATH="/run/containerd/containerd.sock"
          sudo -u root -E env "PATH=$PATH" "NIX_PATH=$NIX_PATH" nix build -L --option sandbox false '.#${{ matrix.attr }}'
